version: "3.7"

services:

  nest_server:
    build:
      context: ./nest-server
    ports:
     - "3040:3040"
    depends_on:
     - db
    #  - redis
    volumes:
      - ./nest-server:/usr/src/app
      - my_nest_node_modules:/usr/src/app/node_modules
    networks:
     - backend

  # fe_article_server:
  #   build:
  #     context: ./server
  #   ports:
  #    - "7002:7001"
  #   depends_on:
  #    - db
  #    - redis
  #   networks:
  #    - backend

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=article
      - MYSQL_USER=worker
      - MYSQL_PASSWORD=wptworker
      - MYSQL_ROOT_PASSWORD=wptroot
      - TZ=UTC
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d:ro
      - ./db/logs:/var/log/mysql:rw
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
     - backend

  nginx:
    build:
      context: ./webapp
    ports: 
      - "3030:80"
    volumes:
      # - ./webapp/dist:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/log/error.log:/var/log/nginx/error.log
    networks:
      - backend
    restart: always
    container_name: nginx
  
  # redis:
  #   build: ./redis
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - ./redis/redis.conf/:/usr/local/etc/redis.conf
  #     - ./redis/data:/usr/local/redis/data
  #     # - ./redis/redis.log:/usr/local/redis/redis.log
  #   restart: always
  #   container_name: redis
  #   networks:
  #     - backend

networks:
  backend:
volumes:
  my_nest_node_modules:
